DROP TABLE IF EXISTS raffleTicket;

CREATE SEQUENCE RAFFLE_SEQ INCREMENT BY 1; 

create table RAFFLE_TICKET
(

   RAFFLE_TICKET_ID integer not null,
   RAFFLE_KEY varchar(255) not null,
   SID varchar(255) not null,
   WINNER BOOLEAN DEFAULT FALSE,
   primary key(RAFFLE_TICKET_ID),
   unique key sid_unique(SID),
   unique key raffle_id_unique(RAFFLE_KEY),
   unique key sid_raffle_unique (RAFFLE_KEY, SID)

);

INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '12345', 'A123456', FALSE);  
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '23456', 'B123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '34567', 'C123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '45678', 'D123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '56789', 'E123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '67890', 'F123456', FALSE);  
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '78901', 'G123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '89012', 'H123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '90123', 'I123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '01234', 'J123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '112233', 'K123456', FALSE);  
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '223344', 'L123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '334455', 'M123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '445566', 'N123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '556677', 'O123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '667788', 'P123456', FALSE);  
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '778899', 'Q123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '889900', 'R123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '990011', 'S123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '001122', 'T123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '111222', 'U123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '222333', 'V123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '333444', 'W123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '444555', 'X123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '555666', 'Y123456', FALSE);
INSERT INTO RAFFLE_TICKET (RAFFLE_TICKET_ID, RAFFLE_KEY, SID, WINNER ) VALUES (NEXTVAL('RAFFLE_SEQ'), '666777', 'Z123456', FALSE);


